### ISSUE TITLE
How can I use webrepl on esp32

### ISSUE THREAD

**Issue by biaoxiaoduan** [micropython/micropython-esp32#169] opened 2017-08-29 08:46 UTC
I tried to use web repl on esp32, but I found that ESP32 does not have uos.dupterm method, which is implemented with api system_os_post on ESP8266. Is there anyone who use web repl on esp32 successfully?

**Comment by MrSurly** [comment] 2017-08-29 14:42
See #107

**Comment by nickzoic** [comment] 2017-09-12 01:10
I'm going to close this one as a duplicate of #107 ... its definitely something we want to implement though!
Thanks for your feedback.

**Closed as completed by nickzoic** 2017-09-12 01:10 UTC
